version: "3.3"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8020:8000
  nginx:
    image: nginx:1.19-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_content:/var/www/pdf_generator
    ports:
      - 80:80
      - 444:443
    depends_on:
      - web

volumes:
  pgdata: {}
  static_content: {}
