# Generated by Django 3.1 on 2021-02-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
