# Generated by Django 3.1 on 2021-02-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0002_auto_20210219_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='number',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
