# Generated by Django 3.1 on 2021-02-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0005_auto_20210220_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterField(
            model_name='designation',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
