# Generated by Django 3.1 on 2021-03-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0006_auto_20210223_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='bic_swift',
            field=models.TextField(default='CRESCHZZ80A', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='iban',
            field=models.TextField(default='CH26 0483 5216 7077 3100 0', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='kontonummer',
            field=models.TextField(default='2167077-32', max_length=32, null=True),
        ),
    ]
