# Generated by Django 3.1 on 2021-03-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0007_auto_20210301_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='bemerkung',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
