# Generated by Django 3.1 on 2021-03-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0009_auto_20210303_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='bic_swift',
            field=models.TextField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='iban',
            field=models.TextField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='kontonummer',
            field=models.TextField(max_length=32, null=True),
        ),
    ]
