# Generated by Django 3.1 on 2021-03-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0010_auto_20210303_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='bemerkung',
            field=models.TextField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='bic_swift',
            field=models.TextField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='client_address',
            field=models.TextField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='client_name',
            field=models.TextField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='iban',
            field=models.TextField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='kontonummer',
            field=models.TextField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
