# Generated by Django 3.1 on 2021-03-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0012_auto_20210303_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
