# Generated by Django 3.1 on 2021-03-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0015_auto_20210319_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='send',
            field=models.BooleanField(default=False),
        ),
    ]
