# Generated by Django 3.1 on 2021-04-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0018_auto_20210406_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerconfirmation',
            name='signed_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
