# Generated by Django 3.1 on 2021-04-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0020_auto_20210408_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='name',
            field=models.TextField(default=6),
            preserve_default=False,
        ),
    ]
