# Generated by Django 3.1 on 2021-06-10 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0022_auto_20210409_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('write_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.TextField(max_length=128)),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
                'ordering': ['-create_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-create_date'], 'verbose_name': 'Rechnung', 'verbose_name_plural': 'Rechnugen'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-create_date'], 'verbose_name': 'Offerte', 'verbose_name_plural': 'Offerten'},
        ),
        migrations.AlterModelOptions(
            name='offerconfirmation',
            options={'ordering': ['-create_date'], 'verbose_name': 'Auftragsbestätigung', 'verbose_name_plural': 'Auftragsbestätigungen'},
        ),
        migrations.AlterModelOptions(
            name='paymentinformation',
            options={'ordering': ['-create_date'], 'verbose_name': 'Zahlungsinformation', 'verbose_name_plural': 'Zahlungsinformationen'},
        ),
        migrations.AlterModelOptions(
            name='signature',
            options={'ordering': ['-create_date'], 'verbose_name': 'Signatur', 'verbose_name_plural': 'Signaturen'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='pdf_generator.category'),
        ),
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='pdf_generator.category'),
        ),
        migrations.AddField(
            model_name='offerconfirmation',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_confirmations', to='pdf_generator.category'),
        ),
    ]
