# Generated by Django 3.1 on 2021-06-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0023_auto_20210610_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
