# Generated by Django 3.1 on 2021-06-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0024_offer_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='send',
            new_name='sent',
        ),
        migrations.RenameField(
            model_name='offerconfirmation',
            old_name='send',
            new_name='sent',
        ),
    ]
