# Generated by Django 3.1 on 2021-06-12 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0025_auto_20210611_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='price',
        ),
    ]
