# Generated by Django 3.1 on 2021-06-12 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0026_remove_offer_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('write_date', models.DateTimeField(auto_now=True, null=True)),
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('client_address', models.TextField(max_length=512, null=True)),
                ('client_name', models.TextField(max_length=128, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('description', models.TextField(max_length=512, null=True)),
                ('bemerkung', models.TextField(blank=True, max_length=512, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField(max_length=512, unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='pdf_generator.category')),
                ('payment_information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='pdf_generator.paymentinformation')),
                ('signature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='pdf_generator.signature')),
            ],
            options={
                'verbose_name': 'Vorlage',
                'verbose_name_plural': 'Vorlagen',
                'ordering': ['-create_date'],
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='pdf_generator.template'),
        ),
    ]
