# Generated by Django 3.1 on 2021-06-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0029_auto_20210614_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='nach_aufwand',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='designation',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
