# Generated by Django 3.1 on 2021-06-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0030_auto_20210617_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerconfirmation',
            name='schlusstext',
            field=models.TextField(blank=True, default='Wir bedanken uns für den Auftrag und freuen uns auf eine erfolgreiche Zusammenarbeit. \nBitte senden Sie dieses Dokument gegengezeichnet an uns uruck.', max_length=512, null=True),
        ),
    ]
