# Generated by Django 3.1 on 2021-07-05 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0032_auto_20210705_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designations', to='pdf_generator.hourlyrate'),
        ),
    ]
