# Generated by Django 3.1 on 2021-09-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0033_auto_20210705_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='hours_to_months',
            field=models.BooleanField(default=False),
        ),
    ]
