# Generated by Django 3.1 on 2021-10-27 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0036_auto_20211027_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globaltexts',
            options={'ordering': ['-create_date'], 'verbose_name': 'Globaler Text', 'verbose_name_plural': 'Globale Texte'},
        ),
        migrations.AddField(
            model_name='template',
            name='global_texts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='pdf_generator.globaltexts'),
        ),
    ]
