# Generated by Django 3.1 on 2021-10-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0039_auto_20211028_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='title',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='offerconfirmation',
            name='title',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
