# Generated by Django 3.1 on 2021-10-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0041_auto_20211029_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='main',
            field=models.BooleanField(default=True),
        ),
    ]
