# Generated by Django 3.1 on 2021-11-01 11:24

from django.db import migrations


def fill_in_the_field_main(apps, schema_editor):
    Phase = apps.get_model('pdf_generator', 'Phase')
    for phase in Phase.objects.all():
        if phase.main is None or phase.main == '':
            phase.main = True
            phase.save(update_fields=['main'])


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0042_phase_main'),
    ]

    operations = [
        migrations.RunPython(fill_in_the_field_main),
    ]
