# Generated by Django 3.1 on 2021-11-03 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0045_auto_20211103_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='without_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='pdf_generator.invoice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='pdf_generator.offer'),
        ),
    ]
