# Generated by Django 3.1 on 2021-11-03 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0046_auto_20211103_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='pdf_generator.category'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_amount_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='mwst',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='netto_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='zahlbar_bis',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
