# Generated by Django 3.1 on 2021-11-03 18:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0048_auto_20211103_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment_information',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='without_offer',
        ),
        migrations.RemoveField(
            model_name='page',
            name='invoice',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='pdf_generator.category'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_amount_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='mwst',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='netto_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='offer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='pdf_generator.offer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='zahlbar_bis',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='InvoiceWithoutOffer',
            fields=[
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('write_date', models.DateTimeField(auto_now=True, null=True)),
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('client_address', models.TextField(max_length=512, null=True)),
                ('client_name', models.TextField(max_length=128, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('title', models.TextField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(max_length=512, null=True)),
                ('iban', models.TextField(default='CH26 0483 5216 7077 3100 0', max_length=32, null=True)),
                ('bic_swift', models.TextField(default='CRESCHZZ80A', max_length=32, null=True)),
                ('kontonummer', models.TextField(default='2167077-32', max_length=32, null=True)),
                ('bemerkung', models.TextField(blank=True, max_length=512, null=True)),
                ('zahlbar_bis', models.DateTimeField(blank=True, null=True)),
                ('netto_price', models.IntegerField(blank=True, null=True)),
                ('mwst', models.IntegerField(blank=True, null=True)),
                ('invoice_amount_total', models.IntegerField(blank=True, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_without_offer', to='pdf_generator.category')),
                ('global_texts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_without_offer', to='pdf_generator.globaltexts')),
                ('payment_information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_without_offer', to='pdf_generator.paymentinformation')),
                ('signature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_without_offer', to='pdf_generator.signature')),
            ],
            options={
                'verbose_name': 'Rechnung ohne Offerte',
                'verbose_name_plural': 'Rechnungen ohne Offerten',
                'ordering': ['-create_date'],
            },
        ),
        migrations.AddField(
            model_name='page',
            name='invoice_without_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='pdf_generator.invoicewithoutoffer'),
        ),
    ]
