# Generated by Django 3.1 on 2021-11-03 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0049_auto_20211103_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicewithoutoffer',
            name='signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_without_offer', to='pdf_generator.signature'),
        ),
    ]
