# Generated by Django 3.1 on 2021-11-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0050_auto_20211103_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-create_date'], 'verbose_name': 'Rechnung', 'verbose_name_plural': 'Rechnungen'},
        ),
        migrations.AlterField(
            model_name='designation',
            name='number_of_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='designation',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_amount_total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='invoicewithoutoffer',
            name='invoice_amount_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offerconfirmation',
            name='invoice_amount_total',
            field=models.FloatField(null=True),
        ),
    ]
