# Generated by Django 3.1 on 2021-12-24 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0053_auto_20211223_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicewithoutoffer',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_without_offer', to='pdf_generator.template'),
        ),
    ]
