# Generated by Django 3.1 on 2021-12-24 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0054_invoicewithoutoffer_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicewithoutoffer',
            name='bic_swift',
            field=models.TextField(blank=True, default='CRESCHZZ80A', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='invoicewithoutoffer',
            name='client_address',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='invoicewithoutoffer',
            name='client_name',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='invoicewithoutoffer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='invoicewithoutoffer',
            name='iban',
            field=models.TextField(blank=True, default='CH26 0483 5216 7077 3100 0', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='invoicewithoutoffer',
            name='kontonummer',
            field=models.TextField(blank=True, default='2167077-32', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='invoicewithoutoffer',
            name='payment_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_without_offer', to='pdf_generator.paymentinformation'),
        ),
    ]
