# Generated by Django 3.1 on 2022-01-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0055_auto_20211224_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='create_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='write_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='create_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='write_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='globaltexts',
            name='create_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='globaltexts',
            name='write_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hourlyrate',
            name='create_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hourlyrate',
            name='write_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='create_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='write_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicewithoutoffer',
            name='create_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicewithoutoffer',
            name='write_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='create_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='write_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offerconfirmation',
            name='create_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offerconfirmation',
            name='write_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='create_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='write_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='create_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='write_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='create_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='write_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='create_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='write_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='create_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='write_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
