# Generated by Django 3.1 on 2022-01-10 09:02

from django.db import migrations


def change_datetime_to_date(apps, schema_editor):
    GlobalTexts = apps.get_model('pdf_generator', 'GlobalTexts')
    HourlyRate = apps.get_model('pdf_generator', 'HourlyRate')
    Signature = apps.get_model('pdf_generator', 'Signature')
    PaymentInformation = apps.get_model('pdf_generator', 'PaymentInformation')
    Category = apps.get_model('pdf_generator', 'Category')
    Template = apps.get_model('pdf_generator', 'Template')
    Offer = apps.get_model('pdf_generator', 'Offer')
    Invoice = apps.get_model('pdf_generator', 'Invoice')
    InvoiceWithoutOffer = apps.get_model('pdf_generator', 'InvoiceWithoutOffer')
    OfferConfirmation = apps.get_model('pdf_generator', 'OfferConfirmation')
    Page = apps.get_model('pdf_generator', 'Page')
    Phase = apps.get_model('pdf_generator', 'Phase')
    Designation = apps.get_model('pdf_generator', 'Designation')

    models_list = [
        GlobalTexts, HourlyRate, Signature, PaymentInformation, Category, Template, Offer, Invoice, InvoiceWithoutOffer,
        OfferConfirmation, Page, Phase, Designation
    ]

    for model in models_list:
        for obj in model.objects.all():
            obj.create_date = obj.create_date.split(sep=' ')[0]
            obj.write_date = obj.write_date.split(sep=' ')[0]
            obj.save(update_fields=['create_date', 'write_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0056_auto_20220110_0857'),
    ]

    operations = [
        migrations.RunPython(change_datetime_to_date),
    ]
