# Generated by Django 3.1 on 2022-01-10 09:17

from django.db import migrations


def change_datetime_to_date(apps, schema_editor):
    Invoice = apps.get_model('pdf_generator', 'Invoice')
    InvoiceWithoutOffer = apps.get_model('pdf_generator', 'InvoiceWithoutOffer')
    OfferConfirmation = apps.get_model('pdf_generator', 'OfferConfirmation')

    models_list = [
        Invoice, InvoiceWithoutOffer, OfferConfirmation
    ]

    for model in models_list:
        for obj in model.objects.all():
            obj.zahlbar_bis = obj.zahlbar_bis.split(sep=' ')[0]
            obj.save(update_fields=['zahlbar_bis'])


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0059_auto_20220110_0917'),
    ]

    operations = [
        migrations.RunPython(change_datetime_to_date),
    ]
