# Generated by Django 3.1 on 2022-01-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0060_auto_20220110_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='zahlbar_bis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicewithoutoffer',
            name='zahlbar_bis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offerconfirmation',
            name='zahlbar_bis',
            field=models.DateField(blank=True, null=True),
        ),
    ]
