# Generated by Django 3.1 on 2022-01-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0061_auto_20220110_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='page_break',
            field=models.BooleanField(default=False),
        ),
    ]
